#!/bin/bash

. $HOME/.profile_armnlib
. r.load.dot dev/gfortran

export PYTHONPATH=$PWD/lib:$PYTHONPATH
export rpnpy=$PWD
export CMCGRIDF=$ATM_MODEL_DFILES/bcmk

#python -m pytest --maxfail=2
set -x
cd
#find . -name vgrid.c
cd vgrid
git checkout -b 6.4.b2_CI origin/6.4.b2_CI
cd src
make
cd ../tests
make tests
